# Travis-CI Build for the OpenRA website
# see travis-ci.org for details

# Same version as the open-ra.org webserver.
language: ruby
rvm:
  - 1.8.7

install:
 - gem install nanoc kramdown

script:
 - nanoc compile

# Only watch the production branch.
branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc: "irc.freenode.net#openra"